const $=s=>document.querySelector(s), content=$('#content');
let market=[], office=[];
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const money=v=>new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR'}).format(v||0);
async function get(u){const r=await fetch(u); if(!r.ok) throw new Error('HTTP '+r.status); return r.json()}
async function post(u,body){const r=await fetch(u,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}); return r.json()}
function nav(){document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.view)})}
function shell(title,sub,body,action=''){content.innerHTML=`<section class="page"><div class="page-head"><div><div class="crumb">CRYPTO AI / COMMAND CENTER</div><h1>${title}</h1><p>${sub}</p></div>${action}</div>${body}</section>`}
function ticker(){ $('#topTicker').innerHTML=market.map(x=>`<div class="ticker-item"><b>${x.symbol}</b><span>$${Number(x.price).toLocaleString('en-US',{maximumFractionDigits:x.price<10?4:2})}</span><i class="${x.change>=0?'up':'down'}">${x.change>=0?'+':''}${x.change.toFixed(2)}%</i></div>`).join('') }
function statusLabel(s){return s==='working'?'TRABALHANDO':s==='blocked'?'BLOQUEADO':s==='idle'?'EM ESPERA':'VAGA ABERTA'}
function desk(a){const control=a.status==='vacancy'?`<button class="mini-btn" disabled>VAGA</button>`:`<button class="mini-btn" onclick="toggleAgent('${a.id}','${a.status==='working'?'pause':'start'}')">${a.status==='working'?'PAUSAR':'TRABALHAR'}</button>`; return `<article class="agent-card ${a.status}"><div class="agent-head"><div class="agent-icon">${a.name.slice(0,2).toUpperCase()}</div><span class="agent-status ${a.status}"><i></i>${statusLabel(a.status)}</span></div><h3>${esc(a.name)}</h3><div class="role">${esc(a.role)}</div><p>${esc(a.activity)}</p><div class="skill"><span>SKILL</span><b>${a.skill||'—'}</b><div><i style="width:${a.skill||8}%"></i></div></div><div class="agent-actions">${control}${a.name==='Executor'&&a.status==='blocked'?`<button class="mini-btn paper" onclick="authorizePaper('${a.id}')">AUTORIZAR PAPER</button>`:''}${a.status!=='vacancy'?`<button class="mini-btn danger" onclick="blockAgent('${a.id}')">BLOQUEAR</button>`:''}</div></article>`}
async function load(){try{market=(await get('/api/market')).assets;office=(await get('/api/office')).agents;ticker();render('dashboard')}catch(e){content.innerHTML='<div class="fatal">Falha ao carregar o Command Center.</div>'}}
async function refreshData(){try{market=(await get('/api/market')).assets;office=(await get('/api/office')).agents;ticker(); if(document.querySelector('.page')) render(document.querySelector('.nav.active')?.dataset.view||'dashboard')}catch(e){}}
async function toggleAgent(id,action){const r=await post('/api/agents/action',{agent_id:id,action}); if(r.ok) await refreshData(); else alert(r.message)}
async function authorizePaper(id){const r=await post('/api/agents/action',{agent_id:id,action:'authorize_paper'}); if(r.ok) await refreshData(); else alert(r.message)}
async function blockAgent(id){if(!confirm('Bloquear este agente?')) return; const r=await post('/api/agents/action',{agent_id:id,action:'block'}); if(r.ok) await refreshData(); else alert(r.message)}
function dashboard(){const active=office.filter(x=>x.status==='working').length, blocked=office.filter(x=>x.status==='blocked').length, vacancies=office.filter(x=>x.status==='vacancy').length; const live=market[0]; shell('Command Center','Sala de trabalho visual dos agentes, mercado e controlo do Owner',`<div class="hero-grid"><div class="metric-strip"><div><span>ROBÔS NO ESCRITÓRIO</span><b>${office.length}</b><small>${office.length-vacancies} ativos/registados · ${vacancies} vagas</small></div><div><span>A TRABALHAR</span><b>${active}</b><small>atividade atual</small></div><div><span>BLOQUEADOS</span><b class="red">${blocked}</b><small>Governance</small></div><div><span>BTC</span><b>${live?'$'+Number(live.price).toLocaleString('en-US',{maximumFractionDigits:0}):'—'}</b><small class="${live?.change>=0?'up':'down'}">${live?live.change.toFixed(2)+'%':''}</small></div></div></div><div class="dashboard-grid"><section class="office-frame"><div class="section-bar"><div><b>ESCRITÓRIO</b><span>Postos reais do sistema · atualização automática</span></div><span class="clock" id="clock"></span></div><div class="pixel-office"><img src="/static/assets/office.png" alt="Escritório pixel art"><div class="office-hud"><span>● LIVE DATA</span><span>● PAPER READY</span><span>● LIVE TRADING OFF</span></div></div><div class="agent-grid">${office.map(desk).join('')}</div></section><aside class="right-column"><div class="panel portfolio-panel"><div class="panel-title">PATRIMÓNIO <span>TESTE</span></div><div class="big-money" id="dashValue">€ 1.250,00</div><div class="stat-line"><span>Investido</span><b id="dashInvested">€ 0,00</b></div><div class="stat-line"><span>Resultado</span><b class="up" id="dashPnl">€ 0,00</b></div><div class="stat-line"><span>Retorno</span><b class="up" id="dashPct">0,00%</b></div></div><div class="panel broker-panel"><div class="panel-title">CORRETORA <span class="online">● MODO PAPER</span></div><strong>Conta não conectada</strong><p>Integração de corretora preparada, sem envio de ordens LIVE.</p><button class="wide-btn" onclick="go('broker')">ABRIR CORRETORA</button></div><div class="panel chat-mini"><div class="panel-title">CHAT COM O CHEFE <span>●</span></div><div class="bubble">Olá. Sou o Manager. Posso coordenar Scanner + Risk e explicar as decisões.</div><button class="wide-btn" onclick="go('chat')">ABRIR CHAT</button></div></aside></div>`);updateClock();loadDashPortfolio()}
async function loadDashPortfolio(){try{const p=await get('/api/portfolio');$('#dashValue').textContent=money(p.value);$('#dashInvested').textContent=money(p.invested);$('#dashPnl').textContent=(p.pnl>=0?'+ ':'')+money(p.pnl);$('#dashPct').textContent=(p.pnl>=0?'+':'')+p.pnl_pct.toFixed(2)+'%'}catch(e){}}
function updateClock(){const el=$('#clock');if(el){el.textContent=new Date().toLocaleTimeString('pt-PT');setTimeout(updateClock,1000)}}
function marketView(){shell('Mercado','Dados públicos para pesquisa e análise. Sem execução automática.',`<div class="market-grid">${market.map(x=>`<div class="market-card"><div class="coin"><b>${x.symbol}</b><span>${x.source}</span></div><strong>$${Number(x.price).toLocaleString('en-US',{maximumFractionDigits:x.price<10?4:2})}</strong><em class="${x.change>=0?'up':'down'}">${x.change>=0?'+':''}${x.change.toFixed(2)}%</em><div class="spark"><i style="height:${30+Math.abs(x.change)*8}%"></i><i style="height:${45+Math.abs(x.change)*5}%"></i><i style="height:${35+Math.abs(x.change)*10}%"></i><i style="height:${55+Math.abs(x.change)*4}%"></i><i style="height:${50+Math.abs(x.change)*7}%"></i></div></div>`).join('')}</div><div class="panel note"><b>Fonte</b><p>O backend tenta Binance 24h e usa CoinGecko/fallback quando necessário. O frontend não contém chaves privadas.</p></div>`)}
async function portfolio(){let p=await get('/api/portfolio'); shell('Portfólio','Conta PAPER para testar o fluxo antes de qualquer integração LIVE',`<div class="metric-strip"><div><span>VALOR ATUAL</span><b>${money(p.value)}</b></div><div><span>CAIXA</span><b>${money(p.cash)}</b></div><div><span>P/L</span><b class="${p.pnl>=0?'up':'red'}">${money(p.pnl)}</b></div><div><span>RETORNO</span><b>${p.pnl_pct.toFixed(2)}%</b></div></div><div class="panel" style="margin-top:16px"><div class="panel-title">POSIÇÕES PAPER</div>${p.positions.length?`<table><thead><tr><th>ATIVO</th><th>QTD</th><th>MÉDIA</th><th>ATUAL</th><th>P/L</th></tr></thead><tbody>${p.positions.map(x=>`<tr><td><b>${x.symbol}</b></td><td>${x.qty}</td><td>$${x.avg_price.toFixed(4)}</td><td>$${x.current.toFixed(4)}</td><td class="${x.pnl>=0?'up':'red'}">${x.pnl.toFixed(2)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Nenhuma posição PAPER. Use Missões ou a área de teste abaixo.</div>'}</div><div class="panel paper-form"><div class="panel-title">SIMULADOR DE ORDEM <span>PAPER ONLY</span></div><div class="form-row"><select id="paperSymbol">${market.map(x=>`<option>${x.symbol}</option>`).join('')}</select><select id="paperSide"><option value="buy">BUY</option><option value="sell">SELL</option></select><input id="paperQty" type="number" step="any" min="0.000001" placeholder="Quantidade"><button class="wide-btn" onclick="paperOrder()">EXECUTAR PAPER</button></div><small>Nenhuma ordem é enviada para a corretora.</small></div>`)}
async function paperOrder(){const r=await post('/api/paper/order',{symbol:$('#paperSymbol').value,side:$('#paperSide').value,qty:Number($('#paperQty').value)});alert(r.ok?`PAPER ${r.side.toUpperCase()} executado a ${r.price}`:r.message);if(r.ok) portfolio()}
function team(){shell('Equipe','Gestão dos funcionários, vagas e permissões do escritório',`<div class="team-grid">${office.map(a=>`<div class="panel team-row"><div><b>${a.name}</b><span>${a.role}</span><small>${a.mission}</small></div><div><strong class="${a.status==='working'?'up':a.status==='blocked'?'red':'amber'}">${statusLabel(a.status)}</strong><button class="mini-btn" onclick="${a.status==='vacancy'?`alert('Vaga aberta: ${esc(a.role)}')`:`toggleAgent('${a.id}','${a.status==='working'?'pause':'start'}')`}">${a.status==='vacancy'?'VER VAGA':a.status==='working'?'PAUSAR':'TRABALHAR'}</button></div></div>`).join('')}</div><div class="panel note"><b>Regra do Owner</b><p>O Manager coordena. Criação de novos agentes, permissões e contratação de vagas continuam dependentes do Owner.</p></div>`)}
function missions(){shell('Missões','Teste o fluxo Manager → Scanner → Risk → Executor em PAPER',`<div class="panel mission-form"><div class="form-row"><input id="objective" placeholder="Ex.: analisar BTC e preparar cenário de risco"><input id="capital" type="number" min="0" placeholder="Capital de teste (€)"><button class="wide-btn" onclick="runMission()">CRIAR MISSÃO</button></div><div id="missionResult" class="result"></div></div><div class="panel"><div class="panel-title">FLUXO</div><div class="flow"><span>OWNER</span><b>→</b><span>MANAGER</span><b>→</b><span>SCANNER</span><b>→</b><span>RISK</span><b>→</b><span>EXECUTOR PAPER</span></div></div>`)}
async function runMission(){const objective=$('#objective').value.trim()||'Analisar o mercado';const capital=Number($('#capital').value||0);const r=await post('/api/missions',{objective,capital});$('#missionResult').innerHTML=`<b>${r.decision}</b>${r.steps.map(s=>`<div class="log-row"><strong>${esc(s.agent)}</strong><span>${esc(s.message)}</span></div>`).join('')}`}
async function reports(){const r=await get('/api/reports');const a=await get('/api/activity');shell('Relatórios','Estado operacional, risco, execução e auditoria',`<div class="report-grid">${r.map(x=>`<div class="panel report"><span class="report-status">${x.status}</span><h3>${x.title}</h3><p>${x.summary}</p></div>`).join('')}</div><div class="panel"><div class="panel-title">ATIVIDADE RECENTE</div>${a.items.map(x=>`<div class="log-row"><strong>${x.agent}</strong><span>${x.text}</span><small>${new Date((x.timestamp||Date.now()/1000)*1000).toLocaleTimeString('pt-PT')}</small></div>`).join('')}</div>`)}
function broker(){shell('Corretora','Ligação preparada. Começamos sempre por READ ONLY.',`<div class="broker-grid"><div class="panel broker-connect"><div class="panel-title">CONTA</div><div class="broker-logo">▣</div><h2>Corretora não conectada</h2><p>Escolha a corretora na próxima etapa e configure as credenciais apenas no backend. Esta interface não envia chaves para o browser.</p><select><option>Selecionar corretora</option><option>Binance</option><option>Kraken</option><option>Coinbase</option><option>Outra</option></select><button class="wide-btn" onclick="alert('Nesta versão a conexão é preparada, mas as credenciais reais ainda não são armazenadas. Primeiro validamos o fluxo PAPER.')">CONFIGURAR READ ONLY</button></div><div class="panel"><div class="panel-title">GOVERNANCE</div><div class="security-list"><div><b>READ ONLY</b><span>Ativo</span></div><div><b>PAPER TRADING</b><span>Permitido</span></div><div><b>LIVE TRADING</b><span class="red">Bloqueado</span></div><div><b>CHAVES NO FRONTEND</b><span class="green">Nunca</span></div></div></div></div>`)}
function chat(){shell('Chat / Chefe','Converse com o Manager e questione o desenvolvimento da equipa',`<div class="chat-layout"><div class="panel chat-area"><div class="messages" id="messages"><div class="bubble"><b>Manager</b><br>Escritório online. Posso coordenar mercado, risco, equipa e PAPER TRADING.</div></div><div class="form-row"><input id="chatInput" placeholder="Pergunte ao chefe..." onkeydown="if(event.key==='Enter')sendChat()"><button class="wide-btn" onclick="sendChat()">ENVIAR</button></div></div><div class="panel"><div class="panel-title">PERGUNTAS RÁPIDAS</div><button class="quick" onclick="quickChat('Qual é o estado do mercado hoje?')">Estado do mercado</button><button class="quick" onclick="quickChat('Qual é o risco atual?')">Risco atual</button><button class="quick" onclick="quickChat('Como está a equipa?')">Estado da equipa</button><button class="quick" onclick="quickChat('Porque o Executor está bloqueado?')">Executor</button></div></div>`)}
async function quickChat(m){$('#chatInput').value=m;await sendChat()}
async function sendChat(){const i=$('#chatInput'),m=i.value.trim();if(!m)return;$('#messages').innerHTML+=`<div class="bubble me">${esc(m)}</div>`;i.value='';const r=await post('/api/chat',{message:m});$('#messages').innerHTML+=`<div class="bubble"><b>${esc(r.speaker)}</b><br>${esc(r.reply)}</div>`;$('#messages').scrollTop=$('#messages').scrollHeight}
function governance(){shell('Governance','Controlo do Owner sobre agentes, permissões e execução',`<div class="report-grid"><div class="panel"><span class="report-status">OWNER</span><h3>Autoridade final</h3><p>O Manager não pode criar nem autorizar agentes sozinho.</p></div><div class="panel"><span class="report-status red">LIVE OFF</span><h3>Execução real</h3><p>Nenhuma ordem LIVE é permitida nesta versão.</p></div><div class="panel"><span class="report-status">PAPER ON</span><h3>Ambiente de testes</h3><p>Ordens simuladas usam dados públicos e não afetam dinheiro real.</p></div><div class="panel"><span class="report-status">AUDIT</span><h3>Rastreabilidade</h3><p>Missões, comandos e ações dos agentes são registados no log operacional.</p></div></div>`)}
function go(v){document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===v));render(v)}
function render(v){if(v==='dashboard')dashboard();else if(v==='market')marketView();else if(v==='portfolio')portfolio();else if(v==='team')team();else if(v==='missions')missions();else if(v==='reports')reports();else if(v==='broker')broker();else if(v==='chat')chat();else governance()}
nav();load();setInterval(refreshData,30000);
